version: "3.8"

services:
  php-test:
    build: .
    container_name: php-unit-test
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    command: vendor/bin/phpunit --testdox --colors=always
